
- name: Flush ALL rules on MAN
  hosts: man
  strategy: free
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: setup
      include_role:
        name: iptables
      vars:
        iptables_rules:
          - flush: yes


- name: Setup DROP rules on MAN
  hosts: man
  strategy: free
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - set_fact:
        private_ip_address_range: ['10.0.0.0/8', '172.16.0.0/12', '224.0.0.0/4']
    - set_fact:
        host_interface: 'eth2'

    - name: setup
      include_role:
        name: iptables
      vars:
        iptables_rules:
          - chain: FORWARD
            destination: '{{ item }}'
            in_interface: '{{ host_interface }}'
            out_interface: eth0
            jump: DROP
      loop: '{{ private_ip_address_range }}'

- name: Update apt packages and install maven
  hosts:
    - smart-meter
    - concentrator
  gather_facts: no
  become: yes
  become_user: root
  tasks:
  - name: Update apt packages
    become: yes
    apt:
      update_cache: yes

  - name: Install maven
    become: yes
    apt:
      pkg:
       - maven

- name: Smart-meter setup
  hosts:
    - smart-meter
  gather_facts: no
  become: yes
  become_user: ubuntu
  tasks: 

  - name: Clone gurux repository
    become: yes
    ansible.builtin.git:
       repo: https://github.com/Gurux/gurux.dlms.java.git
       dest: /home/ubuntu/gurux
       clone: yes

  - name: Create smart-meter
    shell: mvn clean package
    args:
      chdir: /home/ubuntu/gurux/gurux.dlms.server.example.java/

- name: Concentrator setup
  hosts:
    - concentrator
  gather_facts: no
  become: yes
  become_user: ubuntu
  tasks: 

  - name: Clone gurux repository
    become: yes
    ansible.builtin.git:
       repo: https://github.com/Gurux/gurux.dlms.java.git
       dest: /home/ubuntu/gurux
       clone: yes

  - name: Create concentrator
    shell: mvn clean package
    args: 
      chdir: /home/ubuntu/gurux/gurux.dlms.client.example.java/    

- name: Ansible apt module examples
   hosts: all
   become: true
   tasks: 
    - name: Ansible Update Cache and Upgrade all Packages
      register: updatesys
      apt:
        name: "*"
        state: latest
        update_cache: yes

 - name: Playbook to install dsniff,arpspoof-mitm
   hosts: eva
   become: yes
   become_user: root
   tasks: 
    - name: Ansible apt install dsniff
      register: updatesys
      apt:
        update_cache: yes
        name:
          - dsniff     
        state: present

 - name: Playbook s prikazem dsniff
   hosts: eva
   become: yes
   become_user: root
   tasks: 
    - command: 'apt-get install dsniff -y' 

 - name: Playbook to set ipforward
   hosts: eva
   become: yes
   become_user: root
   tasks:
    - command: 'sysctl -w net.ipv4.ip_forward=1' 
#    - name: Set ip forward
#      sysctl:
#        name: net.ipv4.ip_forward
#        value: '{% if ip_forward %}1{% else %}0{% endif %}'
#      when: ip_forward is defined

 - name: Playbook to install HPING3-DDOS
   hosts: eva
   become: yes
   become_user: root
   tasks: 
    - name: Ansible apt install hping3
      register: updatesys
      apt:
        update_cache: yes
        name:
          - hping3
        state: present

 - name: Playbook to install TCPDUMP-REPLY multiple packeges
   hosts: eva
   become: yes
   become_user: root
   tasks:
    - name: Ansible apt to install multiple packages - LAMP - REPLY
      register: updatesys
      apt:
        update_cache: yes
        name:
          - tcpdump
          - tcpreplay
          - bittwist
        state: present